# Generated by Django 5.2.6 on 2025-09-06 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile picture (max 5MB)', null=True, upload_to='profile_pictures/')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('city', models.CharField(blank=True, help_text='Your city (e.g., New York)', max_length=100)),
                ('country', models.CharField(blank=True, help_text='Your country (e.g., United States)', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself (max 500 characters)', max_length=500)),
                ('location', models.CharField(blank=True, help_text='Your city, state/country (e.g., New York, NY)', max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('organization_level', models.CharField(blank=True, choices=[('student', 'Student'), ('junior', 'Junior Level'), ('senior', 'Senior Level'), ('lead', 'Lead Level'), ('director', 'Director Level'), ('executive', 'Executive Level'), ('founder', 'Startup Founder'), ('owner', 'Business Owner')], max_length=20)),
                ('schools', models.TextField(blank=True, help_text='Schools, universities, or educational institutions (one per line or comma-separated)')),
                ('tags', models.TextField(blank=True, help_text='Tags representing your skills, interests, or expertise (comma-separated)')),
                ('name_visibility', models.CharField(choices=[('full', 'Full Name'), ('first_only', 'First Name Only'), ('initials', 'Initials Only'), ('anonymous', 'Anonymous')], default='full', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for authentication', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('coffee_chat_slots', models.PositiveIntegerField(default=5)),
                ('mentorship_slots', models.PositiveIntegerField(default=3)),
                ('networking_slots', models.PositiveIntegerField(default=10)),
                ('general_slots', models.PositiveIntegerField(default=15)),
                ('is_verified', models.BooleanField(default=False, help_text='User can perform actions if verified')),
                ('needs_referrals', models.BooleanField(default=True, help_text='True if user needs 3 referrals to be verified')),
                ('anonymous_name', models.CharField(blank=True, help_text='Anonymous name displayed to other users in community', max_length=100)),
                ('invite_source', models.ForeignKey(blank=True, help_text='User who sent the original invite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text='Email address of the referral recipient', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('recipient_user', models.ForeignKey(blank=True, help_text='User once they register (populated automatically)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_referrals', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sends the referral', on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sender', 'recipient_email')},
            },
        ),
    ]
