# Generated by Django 5.2.6 on 2025-09-04 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile picture (max 5MB)', null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself (max 500 characters)', max_length=500)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('organization_level', models.CharField(blank=True, choices=[('junior', 'Junior Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead/Manager'), ('executive', 'Executive'), ('founder', 'Founder/CEO'), ('student', 'Student'), ('other', 'Other')], max_length=20)),
                ('schools', models.CharField(blank=True, help_text='Schools, universities, or educational institutions', max_length=200)),
                ('tags', models.TextField(blank=True, help_text='Tags representing your skills, interests, or expertise (comma-separated)')),
                ('name_visibility', models.CharField(choices=[('full', 'Full Name'), ('first_only', 'First Name Only'), ('initials', 'Initials Only'), ('anonymous', 'Anonymous')], default='full', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for authentication', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('coffee_chat_slots', models.PositiveIntegerField(default=5)),
                ('mentorship_slots', models.PositiveIntegerField(default=3)),
                ('networking_slots', models.PositiveIntegerField(default=10)),
                ('general_slots', models.PositiveIntegerField(default=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
