# Generated by Django 5.2.6 on 2025-09-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Your city, state/country (e.g., New York, NY)', max_length=100),
        ),
    ]
