# Generated by Django 5.2.6 on 2025-09-10 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the user was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who deleted this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='User is soft deleted (not permanently removed)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='User is temporarily suspended'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='When the user was suspended', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspended_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who suspended this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension'),
        ),
    ]
