# Generated by Django 5.2.6 on 2025-09-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_deleted_at_userprofile_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='When the user was last seen online (webapp access)', null=True),
        ),
    ]
