# Generated by Django 5.2.6 on 2025-09-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_invite_source_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anonymous_name',
            field=models.CharField(blank=True, help_text='Anonymous name displayed to other users in community', max_length=100),
        ),
    ]
