# Generated by Django 5.2.6 on 2025-09-10 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invite_created', 'Invite Created'), ('user_registered', 'User Registered'), ('user_signin', 'User Sign In'), ('user_signout', 'User Sign Out'), ('referral_sent', 'Referral Sent'), ('slot_booked', 'Message Slot Booked'), ('message_answered', 'Message Answered for First Time'), ('user_deleted', 'User Deleted'), ('profile_edited', 'Profile Edited')], help_text='Action that was performed', max_length=50)),
                ('action_detail', models.TextField(blank=True, help_text='Additional details about the action')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the action occurred')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
