# Generated by Django 5.2.6 on 2025-09-14 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrack', '0008_sync_model_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(help_text='URL of the page that gained/lost focus', max_length=500)),
                ('page_title', models.CharField(blank=True, help_text='Title of the page', max_length=200)),
                ('event_type', models.CharField(choices=[('focus_start', 'Page Gained Focus'), ('focus_end', 'Page Lost Focus')], help_text='Type of focus event', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the focus event occurred')),
                ('session_id', models.CharField(blank=True, help_text='Browser session identifier', max_length=100)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True)),
                ('user', models.ForeignKey(help_text='User whose focus is being tracked', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Focus Log',
                'verbose_name_plural': 'Focus Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audittrack__user_id_96de0d_idx'), models.Index(fields=['page_url', 'timestamp'], name='audittrack__page_ur_bcf9e0_idx'), models.Index(fields=['event_type', 'timestamp'], name='audittrack__event_t_c516dc_idx')],
            },
        ),
    ]
