# Generated by Django 5.2.6 on 2025-09-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrack', '0010_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('invite_created', 'Invite Created'), ('user_registered', 'User Registered'), ('user_signin', 'User Sign In'), ('user_signout', 'User Sign Out'), ('referral_sent', 'Referral Sent'), ('slot_booked', 'Message Slot Booked'), ('message_answered', 'Message Answered for First Time'), ('user_deleted', 'User Deleted'), ('profile_edited', 'Profile Edited'), ('user_reported', 'User Reported'), ('user_unblocked', 'User Unblocked'), ('user_suspended', 'User Suspended'), ('user_unsuspended', 'User Unsuspended'), ('user_soft_deleted', 'User Soft Deleted'), ('user_restored', 'User Restored'), ('bulk_user_action', 'Bulk User Action'), ('page_focus_start', 'Page Focus Started'), ('page_focus_end', 'Page Focus Ended'), ('credit_used', 'Credit Used'), ('credit_granted', 'Credit Granted'), ('weekly_credit_reset', 'Weekly Credit Reset')], help_text='Action that was performed', max_length=50),
        ),
    ]
