# Generated by Django 5.2.6 on 2025-09-06 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color_code', models.CharField(default='#00ffff', help_text='Hex color code', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_message_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('receiver_identity_revealed', models.BooleanField(default=False, help_text='True if receiver revealed their identity to sender')),
                ('identity_revealed_at', models.DateTimeField(blank=True, help_text='When identity was revealed', null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('message_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.messagetype')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IdentityRevelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('revealed_to', models.ForeignKey(help_text='User who can now see the real identity', on_delete=django.db.models.deletion.CASCADE, related_name='identity_revelations_received', to=settings.AUTH_USER_MODEL)),
                ('revealer', models.ForeignKey(help_text='User who revealed their identity', on_delete=django.db.models.deletion.CASCADE, related_name='identity_revelations_made', to=settings.AUTH_USER_MODEL)),
                ('message_type', models.ForeignKey(blank=True, help_text='Message type for which identity was revealed', null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.messagetype')),
            ],
            options={
                'ordering': ['-revealed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMessageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_chat_enabled', models.BooleanField(default=True)),
                ('mentorship_enabled', models.BooleanField(default=True)),
                ('networking_enabled', models.BooleanField(default=True)),
                ('general_enabled', models.BooleanField(default=True)),
                ('use_custom_slots', models.BooleanField(default=False, help_text='Use custom message slot types instead of default')),
                ('auto_accept_from_moderators', models.BooleanField(default=False)),
                ('auto_accept_from_admins', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomMessageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for the custom slot type', max_length=50)),
                ('slot_limit', models.PositiveIntegerField(default=5, help_text='Maximum number of slots for this type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_message_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MessageSlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expires_date', models.DateTimeField()),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_booking', to='messaging.message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings_sent', to=settings.AUTH_USER_MODEL)),
                ('message_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='messaging.messagetype')),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['receiver', 'message_type', 'expires_date'], name='messaging_m_receive_373864_idx'), models.Index(fields=['sender', 'receiver', 'message_type'], name='messaging_m_sender__b64732_idx')],
                'unique_together': {('sender', 'receiver', 'message_type')},
            },
        ),
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_message', models.TextField(help_text='Initial message to introduce the conversation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_date', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.conversation')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('message_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='messaging.messagetype')),
            ],
            options={
                'ordering': ['-created_date'],
                'unique_together': {('from_user', 'to_user', 'message_type')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', '-timestamp'], name='messaging_m_sender__5cf9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read', '-timestamp'], name='messaging_m_receive_773742_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='identityrevelation',
            unique_together={('revealer', 'revealed_to', 'message_type')},
        ),
    ]
