# Generated by Django 5.2.6 on 2025-09-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessagesettings',
            name='use_custom_slots',
            field=models.BooleanField(default=True, help_text='Use custom message slot types'),
        ),
    ]
