# Generated by Django 5.2.6 on 2025-09-05 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_fix_created_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expires_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_sender__5cf9ef_idx',
            old_name='messaging_m_sender__e8c4d7_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_receive_773742_idx',
            old_name='messaging_m_receive_1e3a9f_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='messageslotbooking',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_booking', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messageslotbooking',
            name='message_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='messaging.messagetype'),
        ),
        migrations.AddField(
            model_name='messageslotbooking',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageslotbooking',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messageslotbooking',
            index=models.Index(fields=['receiver', 'message_type', 'expires_date'], name='messaging_m_receive_373864_idx'),
        ),
        migrations.AddIndex(
            model_name='messageslotbooking',
            index=models.Index(fields=['sender', 'receiver', 'message_type'], name='messaging_m_sender__b64732_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageslotbooking',
            unique_together={('sender', 'receiver', 'message_type')},
        ),
    ]
