# Generated by Django 5.2.6 on 2025-09-06 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_messageslotbooking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='identity_revealed_at',
            field=models.DateTimeField(blank=True, help_text='When identity was revealed', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_identity_revealed',
            field=models.BooleanField(default=False, help_text='True if receiver revealed their identity to sender'),
        ),
        migrations.CreateModel(
            name='IdentityRevelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('revealed_to', models.ForeignKey(help_text='User who can now see the real identity', on_delete=django.db.models.deletion.CASCADE, related_name='identity_revelations_received', to=settings.AUTH_USER_MODEL)),
                ('revealer', models.ForeignKey(help_text='User who revealed their identity', on_delete=django.db.models.deletion.CASCADE, related_name='identity_revelations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revealed_at'],
                'unique_together': {('revealer', 'revealed_to')},
            },
        ),
    ]
