# Generated by Django 5.2.6 on 2025-09-11 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_chatblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Custom heading/note for this chat (max 100 characters)', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('message_type', models.ForeignKey(blank=True, help_text='Message type for this conversation', null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.messagetype')),
                ('other_user', models.ForeignKey(help_text='The other user in the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='chat_headings_for', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who set this heading', on_delete=django.db.models.deletion.CASCADE, related_name='chat_headings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_date'],
                'unique_together': {('user', 'other_user', 'message_type')},
            },
        ),
    ]
