# Generated by Django 5.2.6 on 2025-09-06 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_identity_revealed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identityrevelation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='identityrevelation',
            name='message_type',
            field=models.ForeignKey(blank=True, help_text='Message type for which identity was revealed', null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.messagetype'),
        ),
        migrations.AlterUniqueTogether(
            name='identityrevelation',
            unique_together={('revealer', 'revealed_to', 'message_type')},
        ),
    ]
