# Generated by Django 5.2.6 on 2025-09-14 21:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_chatheading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('used', 'Credits Used'), ('weekly_reset', 'Weekly Reset'), ('admin_grant', 'Admin Grant'), ('purchase', 'Purchase'), ('bonus', 'Bonus Credits'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.IntegerField(help_text='Positive for grants, negative for usage')),
                ('description', models.TextField(blank=True)),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this transaction (for admin grants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('message_slot_booking', models.ForeignKey(blank=True, help_text='Reference to slot booking if credit was used for messaging', null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.messageslotbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.IntegerField(default=3, help_text='Total available credits (base + purchased + admin granted)')),
                ('base_credits', models.IntegerField(default=3, help_text='Base credits reset weekly (always 3)')),
                ('bonus_credits', models.IntegerField(default=0, help_text='Additional credits from purchases or admin grants')),
                ('credits_used_this_week', models.IntegerField(default=0, help_text='Credits used in current week')),
                ('last_reset_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time credits were reset')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns these credits', on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credit',
                'verbose_name_plural': 'User Credits',
            },
        ),
    ]
