# Generated by Django 5.2.6 on 2025-09-12 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='communities.community'),
        ),
    ]
